name: workshop-potsdam-2022-10
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - dask
  - dask-labextension
  - xarray
  - xarray-simlab=0.5.0
  - netcdf4
  - fastscapelib-f2py=2.8.2
  - ipyfastscape
  - jupyterlab>=3
  - ipykernel
  - ipython
  - matplotlib-base
  - graphviz
  - python-graphviz
  - numba
  - ipywidgets
  - hvplot
  - datashader
  - xarray-spatial
  - zarr
  - tqdm
  - scipy
  - pip
  - pip:
      - git+https://github.com/fastscape-lem/fastscape
